package SJHacks;

public enum Sector {
    ALVISO, BERRYESSA, RINCONGOLDENTRIANGLE, RINCONSOUTH, AIRPORT, ALUMROCK, EVERGREEN, SILVERCREEKVALLEY,
    LITTLEPORTUGAL, OLINDERBONITA, LITTLESAIGON, STORYANDKING, YERBABUENA, MCLAUGHLIN, NORTHMONTEREY,
    SEVENTREEW, EDENVALE, BASKINGRIDGE, SANTATERESA, BLOSSOMVALLEY, ALMADEN, CANOAS, COMMUNICATIONSHILL,
    WILLOWGLEN, CAMBRIAN, BASCOM, FRUITDALE, WINCHESTER, PASEODESARATOGA, CALABAZAS, STEVENSCREEK,
    SANTANAROWVALLEYFAIR, DOWNTOWN, ALMA, COLEMAN, CIVICCENTER, HYDEPARK, JAPANTOWN, MIDTOWN, NAGLEEPARK,
    NORTHSIDE, SPARTANKEYES, SANTOMASAQUINO,TAMIEN, THEALAMEDA, WASHINGTONGUADALUPE, STLEOS, ROSEGARDEN,
    SHASTAHANCHETTPARK;
}
